# Generated by Django 3.0.3 on 2020-02-22 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('road', models.CharField(default='Paved, Gravel, Dirt, or 4x4', max_length=100)),
                ('management', models.CharField(default='Public or Private Land', max_length=100)),
                ('number_of_campsites', models.PositiveIntegerField()),
                ('number_of_days', models.PositiveIntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('author', models.CharField(max_length=200)),
                ('camp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='camping.Camp')),
            ],
        ),
    ]
