# Generated by Django 3.0.3 on 2020-02-22 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('camping', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camp',
            name='management',
        ),
    ]
