# Generated by Django 3.0.3 on 2020-02-22 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camping', '0002_remove_camp_management'),
    ]

    operations = [
        migrations.AddField(
            model_name='camp',
            name='management',
            field=models.CharField(default='Public or Private Land', max_length=100),
        ),
    ]
